### ISSUE TITLE
Upgrade to / optionally use GStreamer 1.0

### ISSUE THREAD

**Issue by johnmurrayvi** [nightingale-media-player/nightingale-hacking#203]
The past couple of days I've looked at GStreamer 1.0 and have done some work on it here:
https://github.com/johnmurrayvi/nightingale-hacking/tree/gst-1.0

Wanted to know if anyone had any opinions or thoughts, etc,
Also, it seems like a good point to look at issue #116 and issue #114

**Comment by freaktechnik** [comment]
What's blocking us from merging in gst 1.0 into trunk? Do the deps build on all platforms (xul-192-gst1)?

**Comment by ilikenwf** [comment]
I believe there are some build flags/considerations? Could probably just make those default. It builds for me here but either due to a change in Archlinux or some other bug, I can not play music with .10 or 1.0.

**Comment by johnmurrayvi** [comment]
Nope... :( not on win iirc.. Never got to finish that. I'm hoping to
actually be able to work on it again soon though

**Comment by PanderMusubi** [comment]
I think this has been solved for 1.13a-0~13186~ubuntu15.04.1

If so, please close this issue. Thanks.

**Comment by freaktechnik** [comment]
Not really, because we switched to a different branch for the ubuntu nightlies, afaik. Same for arch. This doesn't solve this issue.

**Comment by freaktechnik** [comment]
So, there is the little problem, that travis still runs precise atm and doesn't have gst1.0 backports.

**Comment by freaktechnik** [comment]
Okay, travis is no longer a problem. We can use the 14.04 beta environment for builds. So we just have gst1.0 to work on Windows & Mac OS X.

**Comment by PanderMusubi** [comment]
Would a build environment consisting of 15.10 be more suitable?

**Comment by freaktechnik** [comment]
That's not for use to choose. Travis CI is a service which provides free CI and has a set of available environments.
